import { Configuration } from '../../../../app/core/configurator.service';

export const config: Configuration = {
  options: {
    nenb: [
      { value: '0', name: '0' },
      { value: '7', name: '7' },
      { value: '10', name: '10' },
      { value: '11', name: '11' },
      { value: '14', name: '14' },
      { value: '1-6', name: '1-6' },
      { value: '8-13', name: '8-13' },
      { value: '15-28', name: '15-28' },
    ],
    necbe: [
      { value: '0', name: '0' },
      { value: '2-3', name: '2-3' },
      { value: '4-7', name: '4-7' },
      { value: '8-14', name: '8-14' },
      { value: '15-21', name: '15-21' },
      { value: '2', name: '2' },
      { value: '3', name: '3' },
      { value: '4', name: '4' },
      { value: '5', name: '5' },
      { value: '7', name: '7' },
      { value: '8', name: '8' },
      { value: '9', name: '9' },
      { value: '10', name: '10' },
      { value: '11', name: '11' },
      { value: '12', name: '12' },
      { value: '13', name: '13' },
      { value: '14', name: '14' },
      { value: '21', name: '21' },
    ],
    necnl: [
      { value: '0', name: '0' },
      { value: '4-6', name: '4-6' },
      { value: '7-18', name: '7-18' },
      { value: '11-15', name: '11-15' },
      { value: '16-29', name: '16-29' },
      { value: '2', name: '2' },
      { value: '3', name: '3' },
      { value: '4', name: '4' },
      { value: '5', name: '5' },
      { value: '6', name: '6' },
      { value: '7', name: '7' },
      { value: '8', name: '8' },
      { value: '9', name: '9' },
      { value: '10', name: '10' },
      { value: '11', name: '11' },
      { value: '12', name: '12' },
      { value: '13', name: '13' },
      { value: '14', name: '14' },
      { value: '15', name: '15' },
      { value: '16', name: '16' },
      { value: '17', name: '17' },
      { value: '18', name: '18' },
      { value: '19', name: '19' },
      { value: '20', name: '20' },
      { value: '21', name: '21' },
      { value: '22', name: '22' },
      { value: '23', name: '23' },
      { value: '24', name: '24' },
      { value: '25', name: '25' },
      { value: '26', name: '26' },
      { value: '27', name: '27' },
      { value: '28', name: '28' },
      { value: '29', name: '29' },
    ],
  },
};
